### ISSUE TITLE
Create w3id profile

### ISSUE THREAD

**Issue by proycon** [SoftwareUnderstanding/software-iodata#1]
We need a w3id profile for this one

**Comment by proycon** [comment]
(upstream pull request is up)

**Comment by proycon** [comment]
@dgarijo Thanks for the merge, one thing that's still missing is the https://softwareunderstanding.github.io/software-iodata page itself. I guess you have some gh-pages setup on another repo. Could you handle that like you did for software_types?

**Comment by dgarijo** [comment]
Done, apologies, I forgot to set it up!
