### ISSUE TITLE
Determine the scope and review the current proposed solution

### ISSUE THREAD

**Issue by proycon** [SoftwareUnderstanding/software-iodata#2]
This is the continuation of SoftwareUnderstanding/software_types#5 , after we decided to move `consumesData` and `producesData` to a new profile (this one). I already reworked the README and jsonld profile according to some of the comments.

@dgarijo You mentioned a  concern with allowing `CreativeWork` directly as i/o types are most of the time types, not creative works (i.e., instances) per se. And people will likely be confused by this. That and the confusion with type and format too.

I'm not sure if this necessarily has to be a problem if we indicate in the description of `consumesData` and `producesData` that the range is to be typically interpreted as template (and have clear examples as you suggested). This way it does keep things the simplest and keeps this profile as minimal as possible. We could alternatively introduce an extra wrapper classes `InputType` and `OutputType` with a property `template` which points to the `CreativeWork`, but that kind of just moves the problem a level deeper. I think we should consider that only if we want to broaden the scope and have more properties we want to tie directly to `InputType` / `OutputType` (like roles). That might lead to a can of worms though..

**Comment by proycon** [comment]
@dgarijo Gentle reminder; what's your opinion of the current proposed solution in the main branch?

**Comment by dgarijo** [comment]
Thanks for the reminder @proycon. I am currently taking a few days off. Will come back to this by the end of the week

**Comment by dgarijo** [comment]
@proycon please see https://github.com/SoftwareUnderstanding/software-iodata/pull/3/files for small changes. I tried to be more specific and state that the data is either produced in one of the i/o or used (removing the `MAY`). Also fixed a few typos

**Comment by proycon** [comment]
Perfect! Merged!
