### ISSUE TITLE
No redirection for version

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/software-iodata#4]
Right now there is no target for version 1.0.0 when attempting it with content negotiation. If @proycon agrees I can create one

**Comment by proycon** [comment]
Yes, please, that sounds good.

Do we have it properly setup for software-types as well?

**Comment by dgarijo** [comment]
No, I don't think so. I will have a look

**Comment by dgarijo** [comment]
Sorry it took me so long. Now you have the redirection to version 1.0.0 on the releases.
I had to solve conflicts in w3id with your branch. Please don't forget to pull changes if you want to change things.
Oh, and now if you resolve https://w3id.org/software-iodata in the browser

if you want to test: `curl -sH "accept:text/turtle" -L https://w3id.org/software-iodata/1.0.0`

**Comment by proycon** [comment]
Thanks! Looks good!

**Comment by dgarijo** [comment]
Yep, I set up both of them
